---
title: "Citi Bike station map in Jersey City"
output: 
  flexdashboard::flex_dashboard:
    code_folding: hide
    orientation: columns
    vertical_layout: fill
runtime: shiny
---
```{r setup, include=FALSE, echo=FALSE, message=FALSE}
library(flexdashboard)
```


```{r, echo=FALSE, message=FALSE}
library(readr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(leaflet)
library(crosstalk)
library(rvest)
library(httr)
library(plotly)
library(shiny)

data = read.csv("data/bike_data_combined.csv")

map_data = data |>
  select(
    month,
    year,
    start_latitude = start_station_latitude, 
    start_longitude = start_station_longitude,
    end_latitude = end_station_latitude, 
    end_longitude = end_station_longitude) |>
  filter(start_longitude < -74.02, end_longitude < -74.02)

covid_19_testing_centers = read_delim("data/covid_19_testing_centers.csv", delim = ";") |> 
  janitor::clean_names() |> 
  select(latitude, longitude, location_name) |>
  filter(longitude < -74.02, longitude > -74.08 , latitude < 40.75 , latitude > 40.71)

NJ_medical_centers = read_csv("data/NJ_medical_center.csv")

library(shiny)
```
Column {.sidebar}
-----------------------------------------------------------------------

```{r, echo=FALSE, message=FALSE}
selectInput(
  "years", 
  label   = h3("Year"),
  choices = c("2019", "2020"),
  selected = "2019"
)

sliderInput(
  "months",
  label   = h3("Month"),
  min     = 1,
  max     = 12,
  value   = 1,
  step    = 1,
  animate = TRUE
)

selectInput(
  "stations", 
  label   = h3("Stations"),
  choices = c("start", "end"),
  selected = "start"
)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, echo=FALSE}
library(shiny)


renderLeaflet({
  req(input$years, input$months, input$stations)

  year_sel  <- as.integer(input$years)
  month_sel <- month.abb[input$months]
  
  if (input$stations == "start") {
    lat_col      <- "start_latitude"
    long_col     <- "start_longitude"
    legend_title <- "Start Stations"
  } else {
    lat_col      <- "end_latitude"
    long_col     <- "end_longitude"
    legend_title <- "End Stations"
  }

  station_counts <- map_data |>
    filter(
      year  == year_sel,
      month == month_sel
    ) |>
    group_by(
      lat  = .data[[lat_col]],
      long = .data[[long_col]]
    ) |>
    summarise(
      n_trips = n(),
      .groups = "drop"
    )

  bins <- quantile(
    station_counts$n_trips,
    probs = seq(0, 1, length.out = 8),
    na.rm = TRUE
  )
  
  pal <- colorBin(
    palette = c("#4292C6", "#9ECAE1", "#DEEBF7" , "#FFFFBF", "#FDAE61", "#F46D43", "#D73027"),
    domain  = station_counts$n_trips,
    bins    = bins,
    pretty  = FALSE
  )
  
  # Square icon
  svg_content <- paste0(
    '<svg width="10" height="10" xmlns="http://www.w3.org/2000/svg">',
    '<rect x="0" y="0" width="10" height="10" ',
    'style="fill:#228B22;" />', 
    '</svg>'
)
  
  encoded_svg <- URLencode(svg_content, reserved = TRUE)
  square_icon <- makeIcon(
      iconUrl = paste0('data:image/svg+xml;charset=UTF-8,', encoded_svg),
      iconWidth = 8,
      iconHeight = 8,
      iconAnchorX = 5, 
      iconAnchorY = 5
  )
    

  leaflet(station_counts) |>
    addTiles() |>
    setView(lng = -74.051, lat = 40.7203, zoom = 14) |>
    
    
     addMarkers(
      data = covid_19_testing_centers,
      lng = ~longitude,
      lat = ~latitude,
      icon = square_icon, 
      label = ~location_name,
      group = "COVID Centers"
  ) |>

    addAwesomeMarkers(
        data = NJ_medical_centers,
        lng = ~longitude,
        lat = ~latitude,
        
        icon = awesomeIcons(
            icon = "plus",      # Medical sign
            iconColor = "red",
            markerColor = "white", 
            library = "fa"
        ),
        label = ~name,
        group = "Medical Centers"
    ) |> 
    
    addCircleMarkers(
      lng = ~long,
      lat = ~lat,
      radius = 7,
      fillColor = ~pal(n_trips),
      fillOpacity = 0.8,
      stroke = FALSE,
      label = ~paste("Trips:", n_trips),
      group = "Bike Stations"
    ) |>
    
    
    addLegend(
      pal    = pal,
      values = station_counts$n_trips,
      title  = legend_title,
      opacity = 1
    ) |>
    
    addLayersControl(
      overlayGroups = c("Bike Stations", "COVID Centers", "Medical Centers"),
      options = layersControlOptions(collapsed = FALSE)
    )
})


# end station 2020

```
